name: buf
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1.0.3
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
  breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-breaking-action@v1.1.2
        with:
          against: buf.build/bufbuild/reflect
          buf_token: ${{ secrets.BUF_TOKEN }}
  # this module is not manually pushed but managed instead: https://github.com/bufbuild/modules
